[language]
id = "java"
name = "Java"
extensions = ["java"]
comment_line = "//"
comment_start = "/*"
comment_end = "*/"

[brackets]
pairs = [
    ["(", ")"],
    ["[", "]"],
    ["{", "}"],
    ["\"", "\""],
    ["'", "'"],
]

[indentation]
width = 4
use_tabs = false
