[language]
id = "html"
name = "HTML"
extensions = ["html", "htm"]
comment_line = ""
comment_start = "<!--"
comment_end = "-->"

[brackets]
pairs = [
    ["(", ")"],
    ["[", "]"],
    ["{", "}"],
    ["\"", "\""],
    ["'", "'"],
]

[indentation]
width = 4
use_tabs = false
