[language]
id = "typescript"
name = "TypeScript"
extensions = ["ts"]
comment_line = "//"
comment_start = "/*"
comment_end = "*/"

[brackets]
pairs = [
    ["(", ")"],
    ["[", "]"],
    ["{", "}"],
    ["\"", "\""],
    ["'", "'"],
]

[indentation]
width = 4
use_tabs = false
