[language]
id = "css"
name = "CSS"
extensions = ["css"]
comment_line = ""
comment_start = "<!--"
comment_end = "-->"

[brackets]
pairs = [
    ["(", ")"],
    ["[", "]"],
    ["{", "}"],
    ["\"", "\""],
    ["'", "'"],
]

[indentation]
width = 4
use_tabs = false
