[language]
id = "dockerfile"
name = "Dockerfile"
extensions = []
comment_line = "#"
comment_start = ""
comment_end = ""

[brackets]
pairs = [
    ["(", ")"],
    ["[", "]"],
    ["{", "}"],
    ["\"", "\""],
    ["'", "'"],
]

[indentation]
width = 4
use_tabs = false
