[language]
id = "c_sharp"
name = "C#"
extensions = ["cs"]
comment_line = "//"
comment_start = "/*"
comment_end = "*/"

[brackets]
pairs = [
    ["(", ")"],
    ["[", "]"],
    ["{", "}"],
    ["\"", "\""],
    ["'", "'"],
]

[indentation]
width = 4
use_tabs = false
