[language]
id = "cpp"
name = "C++"
extensions = ["cpp", "cc", "cxx", "hpp", "hh", "hxx"]
comment_line = "//"
comment_start = "/*"
comment_end = "*/"

[brackets]
pairs = [
    ["(", ")"],
    ["[", "]"],
    ["{", "}"],
    ["\"", "\""],
    ["'", "'"],
]

[indentation]
width = 4
use_tabs = false
